version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: whatsapp-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      - ./auth_info:/app/auth_info
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:yourpassword@postgres:5432/postgres
      OPENAI_API_KEY: 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
      NODE_ENV: production
      PORT: 3000
      CHAT_HISTORY_LIMIT: 100
      WA_AUTO_RECONNECT: true
      WA_QR_MAX_RETRIES: 3
    env_file:
      - .env
    tty: true               # Allows terminal output (like QR codes)
    stdin_open: true        # Allows interactive input
    restart: unless-stopped # Better restart policy

volumes:
  postgres_data: