version: '3.9'
services:
  chatbot:
    build: ./docker
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GIRLFRIEND_NUMBER=${GIRLFRIEND_NUMBER}
    restart: unless-stopped
